### ISSUE TITLE
The Company Building

### ISSUE THREAD

**Issue by AAlMutwia** [xCursedbreathx/CustomMoonPrices#2]
First of all thank you for making the mod.
Setting it up was easy but I only have one issue with it.
For some reason I can't confirm going to "The Company Building".
I can type "deny" but "confirm" doesn't work.
Can you please fix that since it is quite important to be able to go to the company building to sell scrap.

Thanks in advance.

**Comment by xCursedbreathx** [comment]
Update should be out now thanks for your bug report.

And apologies for the circumstances.
