### ISSUE TITLE
Can't exit terminal bug

### ISSUE THREAD

**Issue by Stratdan** [xCursedbreathx/CustomMoonPrices#6]
When i enter a game, exit, enter again i cannot exit the terminal.
You will know when the bug is triggered when you see the amount of money you have in the corner while you aren't in the terminal

I have no other mods in this example.
Video example:

https://github.com/xCursedbreathx/CustomMoonPrices/assets/85818065/28fed23b-d1eb-4c72-b0b5-3d34b46254df

**Comment by xCursedbreathx** [comment]
Thanks for your bug Report trying to find the issue letting you know when there is a fix

**Comment by xCursedbreathx** [comment]
Have uploaded a Update should be out soon depending on how fast Thunderstore is Reviewing this update.

**Comment by Stratdan** [comment]
Thanks! Terminal works again.
