### ISSUE TITLE
Cant travel to modded moons on versions that allow for them to be changed.

### ISSUE THREAD

**Issue by Eggosss** [xCursedbreathx/CustomMoonPrices#7]
Im not sure if its on your mod or the moon mods or i just misunderstand which moons work with this mod but for some reason when the modded moons prices arent able to be changed i can try traveling but when i can change them it doesnt work for some moons. most of the moons i have are wesley but kast is also not able to be traveled to. The old ruins is able to be traveled to though with the price change. i have two recordings one with the newest version that allows modded price and the other doesnt.

https://github.com/xCursedbreathx/CustomMoonPrices/assets/163368757/6fa7b2b6-6951-4d1e-a214-20c9cad623db

https://github.com/xCursedbreathx/CustomMoonPrices/assets/163368757/a6ff6222-4bd7-4fa2-b5bb-8fa488d3adbd

**Comment by xCursedbreathx** [comment]
I have been able to reproduce the bug, I will work on it and let you know as soon as I have uploaded a new version.

**Comment by xCursedbreathx** [comment]
New Version is uploaded sorry issue has been closed reopnening this until everything works correct

**Comment by Eggosss** [comment]
Works perfect now so far. Thank you!
